/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as RegisterHospitalRouteImport } from './routes/register-hospital'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as HospitalsIndexRouteImport } from './routes/hospitals.index'
import { Route as HospitalsSlugRouteImport } from './routes/hospitals.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register-hospital',
  path: '/register-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsIndexRoute = HospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsSlugRoute = HospitalsSlugRouteImport.update({
  id: '/hospitals/$slug',
  path: '/hospitals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/book/$slug': typeof BookSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/hospitals/': typeof HospitalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/book/$slug': typeof BookSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/hospitals': typeof HospitalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/book/$slug': typeof BookSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/hospitals/': typeof HospitalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/register-hospital'
    | '/book/$slug'
    | '/hospitals/$slug'
    | '/hospitals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/register-hospital'
    | '/book/$slug'
    | '/hospitals/$slug'
    | '/hospitals'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/compare'
    | '/register-hospital'
    | '/book/$slug'
    | '/hospitals/$slug'
    | '/hospitals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  BookSlugRoute: typeof BookSlugRoute
  HospitalsSlugRoute: typeof HospitalsSlugRoute
  HospitalsIndexRoute: typeof HospitalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-hospital': {
      id: '/register-hospital'
      path: '/register-hospital'
      fullPath: '/register-hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/': {
      id: '/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof HospitalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$slug': {
      id: '/hospitals/$slug'
      path: '/hospitals/$slug'
      fullPath: '/hospitals/$slug'
      preLoaderRoute: typeof HospitalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  BookSlugRoute: BookSlugRoute,
  HospitalsSlugRoute: HospitalsSlugRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
