/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as RegisterHospitalRouteImport } from './routes/register-hospital'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AppointmentNumberRouteImport } from './routes/appointment.$number'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as HospitalsIndexRouteImport } from './routes/hospitals.index'
import { Route as HospitalsSlugRouteImport } from './routes/hospitals.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register-hospital',
  path: '/register-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AppointmentNumberRoute = AppointmentNumberRouteImport.update({
  id: '/appointment/$number',
  path: '/appointment/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsIndexRoute = HospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsSlugRoute = HospitalsSlugRouteImport.update({
  id: '/hospitals/$slug',
  path: '/hospitals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/appointment/$number': typeof AppointmentNumberRoute
  '/book/$slug': typeof BookSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/hospitals/': typeof HospitalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/appointment/$number': typeof AppointmentNumberRoute
  '/book/$slug': typeof BookSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/hospitals': typeof HospitalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/register-hospital': typeof RegisterHospitalRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/appointment/$number': typeof AppointmentNumberRoute
  '/book/$slug': typeof BookSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/hospitals/': typeof HospitalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/register-hospital'
    | '/admin'
    | '/dashboard'
    | '/appointment/$number'
    | '/book/$slug'
    | '/hospitals/$slug'
    | '/hospitals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/register-hospital'
    | '/admin'
    | '/dashboard'
    | '/appointment/$number'
    | '/book/$slug'
    | '/hospitals/$slug'
    | '/hospitals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/register-hospital'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/appointment/$number'
    | '/book/$slug'
    | '/hospitals/$slug'
    | '/hospitals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  AppointmentNumberRoute: typeof AppointmentNumberRoute
  BookSlugRoute: typeof BookSlugRoute
  HospitalsSlugRoute: typeof HospitalsSlugRoute
  HospitalsIndexRoute: typeof HospitalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-hospital': {
      id: '/register-hospital'
      path: '/register-hospital'
      fullPath: '/register-hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/appointment/$number': {
      id: '/appointment/$number'
      path: '/appointment/$number'
      fullPath: '/appointment/$number'
      preLoaderRoute: typeof AppointmentNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/': {
      id: '/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof HospitalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$slug': {
      id: '/hospitals/$slug'
      path: '/hospitals/$slug'
      fullPath: '/hospitals/$slug'
      preLoaderRoute: typeof HospitalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  AppointmentNumberRoute: AppointmentNumberRoute,
  BookSlugRoute: BookSlugRoute,
  HospitalsSlugRoute: HospitalsSlugRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
